//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InwardRequest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InwardRequest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.InwardRequest", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWB/ Name of delivery person is Required..
        /// </summary>
        internal static string Error_AWBNameofdeliveryperson {
            get {
                return ResourceManager.GetString("Error_AWBNameofdeliveryperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Business Unit.
        /// </summary>
        internal static string Error_BUName {
            get {
                return ResourceManager.GetString("Error_BUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Courier Name/Hand Delivery .
        /// </summary>
        internal static string Error_CourierNameHandDelivery {
            get {
                return ResourceManager.GetString("Error_CourierNameHandDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Location is Required.
        /// </summary>
        internal static string Error_Location {
            get {
                return ResourceManager.GetString("Error_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Material Category.
        /// </summary>
        internal static string Error_MaterialCategory {
            get {
                return ResourceManager.GetString("Error_MaterialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Material Handed over to.
        /// </summary>
        internal static string Error_MaterialHandedoverto {
            get {
                return ResourceManager.GetString("Error_MaterialHandedoverto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Material Location.
        /// </summary>
        internal static string Error_MaterialLocation {
            get {
                return ResourceManager.GetString("Error_MaterialLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Name of Deliver.
        /// </summary>
        internal static string Error_NameofDeliver {
            get {
                return ResourceManager.GetString("Error_NameofDeliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select an Inward.
        /// </summary>
        internal static string Error_NewInward {
            get {
                return ResourceManager.GetString("Error_NewInward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient 1 Particulars is Required.
        /// </summary>
        internal static string Error_Particulars {
            get {
                return ResourceManager.GetString("Error_Particulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Product Category.
        /// </summary>
        internal static string Error_ProductCategory {
            get {
                return ResourceManager.GetString("Error_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Project Name.
        /// </summary>
        internal static string Error_ProjectName {
            get {
                return ResourceManager.GetString("Error_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach a file.
        /// </summary>
        internal static string Error_Recipient1Attachment {
            get {
                return ResourceManager.GetString("Error_Recipient1Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Attach File.
        /// </summary>
        internal static string Error_Recipient2Attachment {
            get {
                return ResourceManager.GetString("Error_Recipient2Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient 2 Particulars is Required.
        /// </summary>
        internal static string Error_Recipient2Particulars {
            get {
                return ResourceManager.GetString("Error_Recipient2Particulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Name is Required.
        /// </summary>
        internal static string Error_SenderName {
            get {
                return ResourceManager.GetString("Error_SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Type of Material.
        /// </summary>
        internal static string Error_TypeofMaterial {
            get {
                return ResourceManager.GetString("Error_TypeofMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward Details Entered By.
        /// </summary>
        internal static string Grid_Title_PerformedBy {
            get {
                return ResourceManager.GetString("Grid_Title_PerformedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWB/ Name of delivery person.
        /// </summary>
        internal static string Label_AWBNameofdeliveryperson {
            get {
                return ResourceManager.GetString("Label_AWBNameofdeliveryperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWB/ Name of delivery person :.
        /// </summary>
        internal static string Label_AWDNo {
            get {
                return ResourceManager.GetString("Label_AWDNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit:.
        /// </summary>
        internal static string Label_BUName {
            get {
                return ResourceManager.GetString("Label_BUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier Name/Hand Delivery :.
        /// </summary>
        internal static string Label_CourierName {
            get {
                return ResourceManager.GetString("Label_CourierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier Name/Hand Delivery.
        /// </summary>
        internal static string Label_CourierNameHandDelivery {
            get {
                return ResourceManager.GetString("Label_CourierNameHandDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward Date:.
        /// </summary>
        internal static string Label_InwardDate {
            get {
                return ResourceManager.GetString("Label_InwardDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward ID :.
        /// </summary>
        internal static string Label_InwardID {
            get {
                return ResourceManager.GetString("Label_InwardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string Label_Location {
            get {
                return ResourceManager.GetString("Label_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Catecory :.
        /// </summary>
        internal static string Label_MaterialCategory {
            get {
                return ResourceManager.GetString("Label_MaterialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Handed Over to:.
        /// </summary>
        internal static string Label_MaterialHandedoverto {
            get {
                return ResourceManager.GetString("Label_MaterialHandedoverto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Location :.
        /// </summary>
        internal static string Label_MaterialLocation {
            get {
                return ResourceManager.GetString("Label_MaterialLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWB/ Name of delivery person :.
        /// </summary>
        internal static string Label_NameofDeliver {
            get {
                return ResourceManager.GetString("Label_NameofDeliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Inward Type.
        /// </summary>
        internal static string Label_NewInward {
            get {
                return ResourceManager.GetString("Label_NewInward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending with :.
        /// </summary>
        internal static string Label_NextApproverAlias {
            get {
                return ResourceManager.GetString("Label_NextApproverAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Id :.
        /// </summary>
        internal static string Label_OutwardId {
            get {
                return ResourceManager.GetString("Label_OutwardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient 1 Particulars:.
        /// </summary>
        internal static string Label_Particulars {
            get {
                return ResourceManager.GetString("Label_Particulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category:.
        /// </summary>
        internal static string Label_ProductCategory {
            get {
                return ResourceManager.GetString("Label_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name:.
        /// </summary>
        internal static string Label_ProjectName {
            get {
                return ResourceManager.GetString("Label_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward Details Entered By :.
        /// </summary>
        internal static string Label_ProposedBy {
            get {
                return ResourceManager.GetString("Label_ProposedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward Details Entered By :.
        /// </summary>
        internal static string Label_ProposedByAlise {
            get {
                return ResourceManager.GetString("Label_ProposedByAlise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment:.
        /// </summary>
        internal static string Label_Recipient1Attachment {
            get {
                return ResourceManager.GetString("Label_Recipient1Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient 2:.
        /// </summary>
        internal static string Label_Recipient2Alise {
            get {
                return ResourceManager.GetString("Label_Recipient2Alise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment:.
        /// </summary>
        internal static string Label_Recipient2Attachment {
            get {
                return ResourceManager.GetString("Label_Recipient2Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient 2 Particulars :.
        /// </summary>
        internal static string Label_Recipient2Particulars {
            get {
                return ResourceManager.GetString("Label_Recipient2Particulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward Date :.
        /// </summary>
        internal static string Label_RequestDate {
            get {
                return ResourceManager.GetString("Label_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender’s Name : .
        /// </summary>
        internal static string Label_SenderName {
            get {
                return ResourceManager.GetString("Label_SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No:.
        /// </summary>
        internal static string Label_SerialNo {
            get {
                return ResourceManager.GetString("Label_SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Material:.
        /// </summary>
        internal static string Label_TypeofMaterial {
            get {
                return ResourceManager.GetString("Label_TypeofMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient 1.
        /// </summary>
        internal static string Section_Title_RECIPIENT1 {
            get {
                return ResourceManager.GetString("Section_Title_RECIPIENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient 2.
        /// </summary>
        internal static string Section_Title_RECIPIENT2 {
            get {
                return ResourceManager.GetString("Section_Title_RECIPIENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward Request Completed Successfully.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;
        ///If you want to print serial number please click on top of the form&apos;s print button.&lt;/b&gt;.
        /// </summary>
        internal static string Text_CompleteSuccess {
            get {
                return ResourceManager.GetString("Text_CompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went Wrong.
        /// </summary>
        internal static string Text_Error {
            get {
                return ResourceManager.GetString("Text_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward Request save as draft successfully.
        /// </summary>
        internal static string Text_SaveDraftSuccess {
            get {
                return ResourceManager.GetString("Text_SaveDraftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward Request saved as draft successfully.
        /// </summary>
        internal static string Text_SaveSuccess {
            get {
                return ResourceManager.GetString("Text_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward Request is saved successfully..
        /// </summary>
        internal static string Text_Success {
            get {
                return ResourceManager.GetString("Text_Success", resourceCulture);
            }
        }
    }
}
