//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutwardRequest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutwardRequest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.OutwardRequest", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particulars :.
        /// </summary>
        internal static string Assembled_Particulars {
            get {
                return ResourceManager.GetString("Assembled_Particulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select an Action.
        /// </summary>
        internal static string Error_Action {
            get {
                return ResourceManager.GetString("Error_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWD No is Required.
        /// </summary>
        internal static string Error_AWDNo {
            get {
                return ResourceManager.GetString("Error_AWDNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is Required.
        /// </summary>
        internal static string Error_Comment {
            get {
                return ResourceManager.GetString("Error_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier Details is Required.
        /// </summary>
        internal static string Error_CourierDetails {
            get {
                return ResourceManager.GetString("Error_CourierDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select HOD.
        /// </summary>
        internal static string Error_HOD {
            get {
                return ResourceManager.GetString("Error_HOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Inward ID.
        /// </summary>
        internal static string Error_InwardId {
            get {
                return ResourceManager.GetString("Error_InwardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location/Address is Required.
        /// </summary>
        internal static string Error_LocationAddress {
            get {
                return ResourceManager.GetString("Error_LocationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Cost is Required.
        /// </summary>
        internal static string Error_MaterialCost {
            get {
                return ResourceManager.GetString("Error_MaterialCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Date is Required.
        /// </summary>
        internal static string Error_OutwardDate {
            get {
                return ResourceManager.GetString("Error_OutwardDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient 1 Particulars is Required.
        /// </summary>
        internal static string Error_Particulars {
            get {
                return ResourceManager.GetString("Error_Particulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particulars is Required.
        /// </summary>
        internal static string Error_Particulars_Outward {
            get {
                return ResourceManager.GetString("Error_Particulars_Outward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Project Name.
        /// </summary>
        internal static string Error_ProjectName {
            get {
                return ResourceManager.GetString("Error_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient 2 Particulars is Required.
        /// </summary>
        internal static string Error_Recipient2Particulars {
            get {
                return ResourceManager.GetString("Error_Recipient2Particulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Name is Required.
        /// </summary>
        internal static string Error_RecipientName {
            get {
                return ResourceManager.GetString("Error_RecipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Attachment is Required.
        /// </summary>
        internal static string Error_RecipientSingleAttachment {
            get {
                return ResourceManager.GetString("Error_RecipientSingleAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment is required.
        /// </summary>
        internal static string Error_TesterAttachment {
            get {
                return ResourceManager.GetString("Error_TesterAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Type of Material.
        /// </summary>
        internal static string Error_TypeofMaterial {
            get {
                return ResourceManager.GetString("Error_TypeofMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action :.
        /// </summary>
        internal static string Label_Action {
            get {
                return ResourceManager.GetString("Label_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWB/ Name of delivery person :.
        /// </summary>
        internal static string Label_AWDNo {
            get {
                return ResourceManager.GetString("Label_AWDNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment :.
        /// </summary>
        internal static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments :.
        /// </summary>
        internal static string Label_Comments {
            get {
                return ResourceManager.GetString("Label_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier Details :.
        /// </summary>
        internal static string Label_CourierDetails {
            get {
                return ResourceManager.GetString("Label_CourierDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOD :.
        /// </summary>
        internal static string Label_HOD {
            get {
                return ResourceManager.GetString("Label_HOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward ID:.
        /// </summary>
        internal static string Label_InwardId {
            get {
                return ResourceManager.GetString("Label_InwardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Address:.
        /// </summary>
        internal static string Label_LocationAddress {
            get {
                return ResourceManager.GetString("Label_LocationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loction/Address :.
        /// </summary>
        internal static string Label_LoctionAddress {
            get {
                return ResourceManager.GetString("Label_LoctionAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Cost :.
        /// </summary>
        internal static string Label_MaterialCost {
            get {
                return ResourceManager.GetString("Label_MaterialCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending with :.
        /// </summary>
        internal static string Label_NextApproverAlias {
            get {
                return ResourceManager.GetString("Label_NextApproverAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Date :.
        /// </summary>
        internal static string Label_OutwardDate {
            get {
                return ResourceManager.GetString("Label_OutwardDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Id :.
        /// </summary>
        internal static string Label_OutwardId {
            get {
                return ResourceManager.GetString("Label_OutwardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient 1 Particulars :.
        /// </summary>
        internal static string Label_Particulars {
            get {
                return ResourceManager.GetString("Label_Particulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name:.
        /// </summary>
        internal static string Label_ProjectName {
            get {
                return ResourceManager.GetString("Label_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Details Entered By :.
        /// </summary>
        internal static string Label_ProposedBy {
            get {
                return ResourceManager.GetString("Label_ProposedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Details Entered By :.
        /// </summary>
        internal static string Label_ProposedByAlise {
            get {
                return ResourceManager.GetString("Label_ProposedByAlise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient 2 Particulars :.
        /// </summary>
        internal static string Label_Recipient2Particulars {
            get {
                return ResourceManager.GetString("Label_Recipient2Particulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Attachment :.
        /// </summary>
        internal static string Label_RecipientAttachment {
            get {
                return ResourceManager.GetString("Label_RecipientAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Name :.
        /// </summary>
        internal static string Label_RecipientName {
            get {
                return ResourceManager.GetString("Label_RecipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Attachment.
        /// </summary>
        internal static string Label_RecipientSingleAttachment {
            get {
                return ResourceManager.GetString("Label_RecipientSingleAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date :.
        /// </summary>
        internal static string Label_RequestDate {
            get {
                return ResourceManager.GetString("Label_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type :.
        /// </summary>
        internal static string Label_RequestType {
            get {
                return ResourceManager.GetString("Label_RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status :.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment:.
        /// </summary>
        internal static string Label_TesterAttachment {
            get {
                return ResourceManager.GetString("Label_TesterAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment:.
        /// </summary>
        internal static string Label_TesterSingleAttachment {
            get {
                return ResourceManager.GetString("Label_TesterSingleAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Material :.
        /// </summary>
        internal static string Label_TypeofMaterial {
            get {
                return ResourceManager.GetString("Label_TypeofMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hod.
        /// </summary>
        internal static string Section_Title_HOD {
            get {
                return ResourceManager.GetString("Section_Title_HOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        internal static string Section_Title_RECIPIENT {
            get {
                return ResourceManager.GetString("Section_Title_RECIPIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester.
        /// </summary>
        internal static string Section_Title_TESTER {
            get {
                return ResourceManager.GetString("Section_Title_TESTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Request has been Completed Successfully.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;
        ///If you want to print outward request details please click on top of the form&apos;s print button.&lt;/b&gt;.
        /// </summary>
        internal static string Text_CompleteSuccess {
            get {
                return ResourceManager.GetString("Text_CompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went Wrong..
        /// </summary>
        internal static string Text_Error {
            get {
                return ResourceManager.GetString("Text_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Request is HOLD Successfully..
        /// </summary>
        internal static string Text_HoldSuccess {
            get {
                return ResourceManager.GetString("Text_HoldSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Request has been sent for Rework..
        /// </summary>
        internal static string Text_Rework {
            get {
                return ResourceManager.GetString("Text_Rework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Request Saved as Draft Successfully..
        /// </summary>
        internal static string Text_SaveDraftSuccess {
            get {
                return ResourceManager.GetString("Text_SaveDraftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Request Saved as Draft Successfully..
        /// </summary>
        internal static string Text_SaveSuccess {
            get {
                return ResourceManager.GetString("Text_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Request is Saved Successfully..
        /// </summary>
        internal static string Text_Success {
            get {
                return ResourceManager.GetString("Text_Success", resourceCulture);
            }
        }
    }
}
