//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Report {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Report() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Report", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BU.
        /// </summary>
        internal static string Grid_BU {
            get {
                return ResourceManager.GetString("Grid_BU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward Date.
        /// </summary>
        internal static string Grid_InwardDate {
            get {
                return ResourceManager.GetString("Grid_InwardDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward ID.
        /// </summary>
        internal static string Grid_InwardID {
            get {
                return ResourceManager.GetString("Grid_InwardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Done.
        /// </summary>
        internal static string Grid_IsOutwardDone {
            get {
                return ResourceManager.GetString("Grid_IsOutwardDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Category.
        /// </summary>
        internal static string Grid_MaterialCategory {
            get {
                return ResourceManager.GetString("Grid_MaterialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Location.
        /// </summary>
        internal static string Grid_MaterialLocation {
            get {
                return ResourceManager.GetString("Grid_MaterialLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type.
        /// </summary>
        internal static string Grid_MaterialType {
            get {
                return ResourceManager.GetString("Grid_MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Date.
        /// </summary>
        internal static string Grid_OutwardDate {
            get {
                return ResourceManager.GetString("Grid_OutwardDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward ID.
        /// </summary>
        internal static string Grid_OutwardID {
            get {
                return ResourceManager.GetString("Grid_OutwardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category.
        /// </summary>
        internal static string Grid_ProductCategory {
            get {
                return ResourceManager.GetString("Grid_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        internal static string Grid_ProjectName {
            get {
                return ResourceManager.GetString("Grid_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string Grid_SerialNo {
            get {
                return ResourceManager.GetString("Grid_SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester.
        /// </summary>
        internal static string Grid_Tester {
            get {
                return ResourceManager.GetString("Grid_Tester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester Assigned Date.
        /// </summary>
        internal static string Grid_TesterAssignedDate {
            get {
                return ResourceManager.GetString("Grid_TesterAssignedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit :.
        /// </summary>
        internal static string Label_BUName {
            get {
                return ResourceManager.GetString("Label_BUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date :.
        /// </summary>
        internal static string Label_DateValues {
            get {
                return ResourceManager.GetString("Label_DateValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        internal static string Label_ExportToExcel {
            get {
                return ResourceManager.GetString("Label_ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Location :.
        /// </summary>
        internal static string Label_MaterialLocation {
            get {
                return ResourceManager.GetString("Label_MaterialLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name :.
        /// </summary>
        internal static string Label_ProjectName {
            get {
                return ResourceManager.GetString("Label_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number :.
        /// </summary>
        internal static string Label_SerialNumber {
            get {
                return ResourceManager.GetString("Label_SerialNumber", resourceCulture);
            }
        }
    }
}
